name: Build & test

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build and test (Android, Jvm, Js)
        run: region=${{ secrets.region }} clientId=${{ secrets.clientid }} ./gradlew build test jsTest
      - name: Build testapp and test request (iOS)
        run: |
          cd iostests
          xcodebuild clean test -project TestApp.xcodeproj -scheme TestApp -destination "platform=iOS Simulator,OS=16.2,name=iPhone 12" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO region=${{ secrets.region }} clientId=${{ secrets.clientid }}
      - name: Upload test result
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports/
